name: diart
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - python=3.10
  - portaudio=19.6.*
  - pysoundfile=0.12.*
  - ffmpeg[version='<4.4']
  - pip
  - pip:
    - .